import type { CategoryId } from "./categories";
import type { LayoutStyleId } from "./layoutStyles";

/** Which opening animation plays before the invitation — see
 * components/invite/intros/registry.ts. */
export type IntroId =
  | "door"
  | "envelope"
  | "kolam"
  | "split"
  | "bloom"
  | "giftbox"
  | "bottle"
  | "curtain"
  | "scratch"
  | "lanterns"
  | "thoranam"
  | "kasavu"
  | "pookalam"
  | "spotlight"
  | "ringbox"
  | "cradle"
  | "ticket"
  // Botanical garden's own page (components/invite/garden).
  | "glasshouse"
  // Chapel Bells' own page (components/invite/chapel).
  | "chapel"
  // Layout-style openings (components/invite/intros/LayoutIntros.tsx).
  | "gopuram"
  | "marigoldCurtain"
  | "jharokha"
  | "lotusBloom"
  | "mughalDoors"
  | "moonLanterns"
  | "stainedGlass"
  | "foilCard"
  | "sunrise"
  | "candlelight"
  | "balloonPop"
  | "cakeCandles";

/**
 * Non-text template config. Display text (name, tagline, description) lives
 * in messages/{locale}.json under `templates.<id>` — see
 * lib/i18n/templates.ts for the locale-aware accessor.
 */
export interface TemplateConfig {
  id: string;
  category: CategoryId;
  defaultAccent: string;
  defaultFont: string;
  /** Tailwind gradient stops used for the landing page preview card. */
  cardGradient: string;
  cardTextClass: string;
  intro: IntroId;
  /** Wedding templates with their own look after the opening: hero art,
   * section emblems, frames, patterns, invocation and event names (see
   * lib/layoutStyles.ts). Without one, the classic royal-palace layout. */
  layout?: LayoutStyleId;
  /** Sample content to start from (`defaultContent.<seed>` in messages) when
   * it's shared with another template; defaults to the template's own id. */
  seed?: string;
  /** A completely separate page instead of the royal layout (with or
   * without a `layout` style): components/invite/garden or
   * components/invite/chapel. */
  pageLayout?: "garden" | "chapel";
  /** Borrow a layout style's event names (e.g. "church" → Holy Matrimony)
   * without using its look — for templates with their own pageLayout. */
  eventNamesFrom?: LayoutStyleId;
  /** Publishing price in ₹. Leave out to use the default (PRICE_INR in
   * lib/pricing.ts). */
  price?: number;
  /** "Was" price in ₹, shown struck through beside the price. Leave out to
   * use the default (LIST_PRICE_INR in lib/pricing.ts). */
  listPrice?: number;
}

export const TEMPLATES: TemplateConfig[] = [
  // ── Featured: its own page (components/invite/garden), first in the gallery ──
  {
    id: "botanical-garden",
    category: "wedding",
    defaultAccent: "#2F4A2C",
    defaultFont: "classic-serif",
    cardGradient: "from-emerald-100 via-lime-50 to-amber-50",
    cardTextClass: "text-emerald-950",
    intro: "glasshouse",
    pageLayout: "garden",
  },
  {
    id: "chapel-bells",
    category: "wedding",
    defaultAccent: "#1F2A44",
    defaultFont: "classic-serif",
    cardGradient: "from-sky-100 via-stone-50 to-rose-50",
    cardTextClass: "text-slate-900",
    intro: "chapel",
    pageLayout: "chapel",
    eventNamesFrom: "church",
    seed: "christian",
  },
  // ── Premium styles, each with its own layout (lib/layoutStyles.ts) ──
  {
    id: "temple-gopuram",
    category: "wedding",
    defaultAccent: "#9E1B32",
    defaultFont: "royal-cinzel",
    cardGradient: "from-rose-900 via-red-800 to-amber-600",
    cardTextClass: "text-amber-100",
    intro: "gopuram",
    layout: "temple",
    seed: "traditional-gold",
  },
  {
    id: "mandap-marigold",
    category: "wedding",
    defaultAccent: "#C2185B",
    defaultFont: "classic-serif",
    cardGradient: "from-pink-600 via-orange-400 to-amber-300",
    cardTextClass: "text-white",
    intro: "marigoldCurtain",
    layout: "mandap",
    seed: "hindu-north",
  },
  {
    id: "rajwada-palace",
    category: "wedding",
    defaultAccent: "#1E3A8A",
    defaultFont: "royal-cinzel",
    cardGradient: "from-blue-900 via-indigo-800 to-amber-500",
    cardTextClass: "text-amber-100",
    intro: "jharokha",
    layout: "palace",
    seed: "hindu-north",
  },
  {
    id: "lotus-peacock",
    category: "wedding",
    defaultAccent: "#0F766E",
    defaultFont: "elegant-script",
    cardGradient: "from-teal-200 via-emerald-100 to-pink-200",
    cardTextClass: "text-teal-900",
    intro: "lotusBloom",
    layout: "lotus",
    seed: "thoranam-jasmine",
  },
  {
    id: "nikah-emerald",
    category: "wedding",
    defaultAccent: "#0F5132",
    defaultFont: "classic-serif",
    cardGradient: "from-emerald-900 via-emerald-700 to-amber-400",
    cardTextClass: "text-amber-100",
    intro: "mughalDoors",
    layout: "nikah",
    seed: "muslim",
  },
  {
    id: "walima-moonlit",
    category: "wedding",
    defaultAccent: "#C9A227",
    defaultFont: "classic-serif",
    cardGradient: "from-slate-950 via-blue-950 to-indigo-900",
    cardTextClass: "text-amber-100",
    intro: "moonLanterns",
    layout: "moonlit",
    seed: "muslim",
  },
  {
    id: "church-stained-glass",
    category: "wedding",
    defaultAccent: "#7A1F3D",
    defaultFont: "classic-serif",
    cardGradient: "from-stone-100 via-amber-50 to-sky-200",
    cardTextClass: "text-stone-800",
    intro: "stainedGlass",
    layout: "church",
    seed: "christian",
  },
  {
    id: "christian-garden",
    category: "wedding",
    defaultAccent: "#5B7A5A",
    defaultFont: "elegant-script",
    cardGradient: "from-lime-100 via-white to-emerald-100",
    cardTextClass: "text-emerald-900",
    intro: "envelope",
    layout: "garden",
    seed: "christian",
  },
  {
    id: "luxe-editorial",
    category: "wedding",
    defaultAccent: "#111111",
    defaultFont: "luxe-didone",
    cardGradient: "from-neutral-950 via-neutral-800 to-amber-700",
    cardTextClass: "text-amber-100",
    intro: "foilCard",
    layout: "editorial",
    seed: "minimal-modern",
  },
  {
    id: "watercolor-botanical",
    category: "wedding",
    defaultAccent: "#C0674F",
    defaultFont: "elegant-script",
    cardGradient: "from-orange-100 via-rose-50 to-emerald-100",
    cardTextClass: "text-emerald-900",
    intro: "bloom",
    layout: "watercolor",
    seed: "floral-pastel",
  },
  {
    id: "boho-arch",
    category: "wedding",
    defaultAccent: "#B5552E",
    defaultFont: "classic-serif",
    cardGradient: "from-orange-200 via-amber-100 to-stone-200",
    cardTextClass: "text-orange-900",
    intro: "sunrise",
    layout: "arch",
    seed: "beach-boho",
  },
  {
    id: "velvet-gold",
    category: "wedding",
    defaultAccent: "#D4AF37",
    defaultFont: "royal-cinzel",
    cardGradient: "from-rose-950 via-red-900 to-amber-600",
    cardTextClass: "text-amber-100",
    intro: "candlelight",
    layout: "velvet",
    seed: "grand-reception",
  },
  // ── Classic royal-palace layout ──
  {
    id: "traditional-gold",
    category: "wedding",
    defaultAccent: "#b8860b",
    defaultFont: "royal-cinzel",
    cardGradient: "from-amber-200 via-yellow-100 to-red-100",
    cardTextClass: "text-amber-900",
    intro: "kolam",
  },
  {
    id: "minimal-modern",
    category: "wedding",
    defaultAccent: "#C2410C",
    defaultFont: "modern-clean",
    cardGradient: "from-neutral-200 via-white to-neutral-100",
    cardTextClass: "text-neutral-900",
    intro: "split",
  },
  {
    id: "floral-pastel",
    category: "wedding",
    defaultAccent: "#d9738a",
    defaultFont: "classic-serif",
    cardGradient: "from-rose-100 via-pink-50 to-emerald-50",
    cardTextClass: "text-rose-900",
    intro: "bloom",
  },
  {
    id: "elegant-bw",
    category: "wedding",
    defaultAccent: "#111111",
    defaultFont: "elegant-script",
    cardGradient: "from-neutral-900 via-neutral-600 to-neutral-200",
    cardTextClass: "text-white",
    intro: "giftbox",
  },
  {
    id: "beach-boho",
    category: "wedding",
    defaultAccent: "#c2703d",
    defaultFont: "classic-serif",
    cardGradient: "from-orange-100 via-amber-50 to-teal-50",
    cardTextClass: "text-orange-900",
    intro: "bottle",
  },
  {
    id: "silk-curtain",
    category: "wedding",
    defaultAccent: "#c9a54a",
    defaultFont: "royal-cinzel",
    cardGradient: "from-rose-900 via-red-800 to-amber-700",
    cardTextClass: "text-amber-100",
    intro: "curtain",
  },
  {
    id: "scratch-reveal",
    category: "wedding",
    defaultAccent: "#a56c7c",
    defaultFont: "classic-serif",
    cardGradient: "from-violet-200 via-fuchsia-100 to-rose-100",
    cardTextClass: "text-violet-900",
    intro: "scratch",
  },
  {
    id: "lantern-night",
    category: "wedding",
    defaultAccent: "#f2a33a",
    defaultFont: "classic-serif",
    cardGradient: "from-indigo-950 via-blue-900 to-orange-700",
    cardTextClass: "text-amber-100",
    intro: "lanterns",
  },
  {
    id: "thoranam-jasmine",
    category: "wedding",
    defaultAccent: "#e0a526",
    defaultFont: "tamil-classic",
    cardGradient: "from-green-800 via-lime-100 to-amber-100",
    cardTextClass: "text-green-950",
    intro: "thoranam",
  },
  {
    id: "kerala-kasavu",
    category: "wedding",
    defaultAccent: "#b8921f",
    defaultFont: "royal-cinzel",
    cardGradient: "from-amber-50 via-yellow-50 to-amber-200",
    cardTextClass: "text-amber-900",
    intro: "kasavu",
  },
  {
    id: "pookalam",
    category: "wedding",
    defaultAccent: "#e8862a",
    defaultFont: "classic-serif",
    cardGradient: "from-orange-300 via-yellow-200 to-red-300",
    cardTextClass: "text-red-950",
    intro: "pookalam",
  },
  {
    id: "grand-reception",
    category: "wedding",
    defaultAccent: "#e8a33d",
    defaultFont: "elegant-script",
    cardGradient: "from-fuchsia-950 via-purple-900 to-amber-700",
    cardTextClass: "text-amber-100",
    intro: "spotlight",
  },
  {
    id: "anniversary-emerald",
    category: "anniversary",
    defaultAccent: "#0f6e4f",
    defaultFont: "royal-cinzel",
    cardGradient: "from-emerald-200 via-emerald-50 to-yellow-100",
    cardTextClass: "text-emerald-900",
    intro: "envelope",
  },
  {
    id: "valentine-blush",
    category: "valentine",
    defaultAccent: "#c2185b",
    defaultFont: "elegant-script",
    cardGradient: "from-rose-300 via-rose-100 to-red-100",
    cardTextClass: "text-rose-900",
    intro: "envelope",
  },
  {
    id: "proposal-starlit",
    category: "proposal",
    defaultAccent: "#c9a227",
    defaultFont: "elegant-script",
    cardGradient: "from-indigo-300 via-indigo-100 to-amber-100",
    cardTextClass: "text-indigo-900",
    intro: "envelope",
  },
  {
    id: "birthday-confetti",
    category: "birthday",
    defaultAccent: "#e0409a",
    defaultFont: "modern-clean",
    cardGradient: "from-fuchsia-200 via-yellow-100 to-sky-100",
    cardTextClass: "text-fuchsia-900",
    intro: "envelope",
  },
  {
    id: "housewarming-terracotta",
    category: "housewarming",
    defaultAccent: "#b5622a",
    defaultFont: "classic-serif",
    cardGradient: "from-orange-200 via-amber-100 to-lime-100",
    cardTextClass: "text-orange-900",
    intro: "envelope",
  },
  {
    id: "engagement-ring",
    category: "engagement",
    defaultAccent: "#9c3b52",
    defaultFont: "elegant-script",
    cardGradient: "from-rose-200 via-pink-100 to-amber-100",
    cardTextClass: "text-rose-900",
    intro: "ringbox",
  },
  {
    id: "baby-moon",
    category: "baby",
    defaultAccent: "#8a6cc2",
    defaultFont: "classic-serif",
    cardGradient: "from-violet-200 via-pink-100 to-amber-100",
    cardTextClass: "text-violet-900",
    intro: "cradle",
  },
  {
    id: "corporate-ticket",
    category: "corporate",
    defaultAccent: "#2563eb",
    defaultFont: "modern-clean",
    cardGradient: "from-slate-900 via-blue-900 to-sky-700",
    cardTextClass: "text-sky-50",
    intro: "ticket",
    // TEMP: ₹1 for live-payment testing.
    // price: 1,
  },
  // ── Premium styles for the other occasions ──
  {
    id: "engagement-sparkle",
    category: "engagement",
    defaultAccent: "#B8860B",
    defaultFont: "classic-serif",
    cardGradient: "from-amber-100 via-white to-yellow-200",
    cardTextClass: "text-neutral-900",
    intro: "ringbox",
    layout: "sparkle",
    seed: "engagement-ring",
  },
  {
    id: "engagement-thamboolam",
    category: "engagement",
    defaultAccent: "#C2410C",
    defaultFont: "royal-cinzel",
    cardGradient: "from-green-800 via-emerald-700 to-amber-400",
    cardTextClass: "text-neutral-900",
    intro: "thoranam",
    layout: "thamboolam",
    seed: "engagement-ring",
  },
  {
    id: "engagement-rose-garden",
    category: "engagement",
    defaultAccent: "#C0587A",
    defaultFont: "elegant-script",
    cardGradient: "from-rose-100 via-white to-emerald-100",
    cardTextClass: "text-neutral-900",
    intro: "bloom",
    layout: "watercolor",
    seed: "engagement-ring",
  },
  {
    id: "engagement-save-the-date",
    category: "engagement",
    defaultAccent: "#111111",
    defaultFont: "luxe-didone",
    cardGradient: "from-stone-100 via-rose-50 to-neutral-300",
    cardTextClass: "text-neutral-900",
    intro: "foilCard",
    layout: "editorial",
    seed: "engagement-ring",
  },
  {
    id: "engagement-mangni",
    category: "engagement",
    defaultAccent: "#C2185B",
    defaultFont: "royal-cinzel",
    cardGradient: "from-pink-800 via-rose-600 to-amber-400",
    cardTextClass: "text-neutral-900",
    intro: "jharokha",
    layout: "palace",
    seed: "engagement-ring",
  },
  {
    id: "anniversary-golden-jubilee",
    category: "anniversary",
    defaultAccent: "#D4AF37",
    defaultFont: "royal-cinzel",
    cardGradient: "from-yellow-900 via-amber-700 to-yellow-400",
    cardTextClass: "text-neutral-900",
    intro: "candlelight",
    layout: "velvet",
    seed: "anniversary-emerald",
  },
  {
    id: "anniversary-vintage-reel",
    category: "anniversary",
    defaultAccent: "#8B5E3C",
    defaultFont: "classic-serif",
    cardGradient: "from-amber-100 via-orange-50 to-stone-300",
    cardTextClass: "text-neutral-900",
    intro: "envelope",
    layout: "vintage",
    seed: "anniversary-emerald",
  },
  {
    id: "anniversary-wine-roses",
    category: "anniversary",
    defaultAccent: "#9B1B30",
    defaultFont: "classic-serif",
    cardGradient: "from-rose-950 via-red-800 to-rose-400",
    cardTextClass: "text-neutral-900",
    intro: "curtain",
    layout: "roses",
    seed: "anniversary-emerald",
  },
  {
    id: "anniversary-silver-jubilee",
    category: "anniversary",
    defaultAccent: "#8A94A6",
    defaultFont: "luxe-didone",
    cardGradient: "from-slate-200 via-white to-slate-300",
    cardTextClass: "text-neutral-900",
    intro: "foilCard",
    layout: "sparkle",
    seed: "anniversary-emerald",
  },
  {
    id: "anniversary-shashtiabdapoorthi",
    category: "anniversary",
    defaultAccent: "#0F5132",
    defaultFont: "royal-cinzel",
    cardGradient: "from-emerald-900 via-green-800 to-amber-500",
    cardTextClass: "text-neutral-900",
    intro: "gopuram",
    layout: "temple",
    seed: "anniversary-emerald",
  },
  {
    id: "valentine-love-letter",
    category: "valentine",
    defaultAccent: "#C8102E",
    defaultFont: "elegant-script",
    cardGradient: "from-red-100 via-white to-sky-100",
    cardTextClass: "text-neutral-900",
    intro: "envelope",
    layout: "letter",
    seed: "valentine-blush",
  },
  {
    id: "valentine-neon-hearts",
    category: "valentine",
    defaultAccent: "#FF3D8B",
    defaultFont: "modern-clean",
    cardGradient: "from-fuchsia-950 via-purple-900 to-pink-600",
    cardTextClass: "text-neutral-900",
    intro: "spotlight",
    layout: "neon",
    seed: "valentine-blush",
  },
  {
    id: "valentine-cupid-clouds",
    category: "valentine",
    defaultAccent: "#E75480",
    defaultFont: "elegant-script",
    cardGradient: "from-pink-200 via-sky-100 to-white",
    cardTextClass: "text-neutral-900",
    intro: "scratch",
    layout: "clouds",
    seed: "valentine-blush",
  },
  {
    id: "valentine-polaroid",
    category: "valentine",
    defaultAccent: "#E4572E",
    defaultFont: "modern-clean",
    cardGradient: "from-orange-100 via-rose-50 to-amber-100",
    cardTextClass: "text-neutral-900",
    intro: "giftbox",
    layout: "vintage",
    seed: "valentine-blush",
  },
  {
    id: "valentine-red-roses",
    category: "valentine",
    defaultAccent: "#D1123F",
    defaultFont: "elegant-script",
    cardGradient: "from-red-900 via-rose-700 to-pink-300",
    cardTextClass: "text-neutral-900",
    intro: "bloom",
    layout: "roses",
    seed: "valentine-blush",
  },
  {
    id: "proposal-starry-night",
    category: "proposal",
    defaultAccent: "#C9A6FF",
    defaultFont: "classic-serif",
    cardGradient: "from-indigo-950 via-violet-900 to-purple-700",
    cardTextClass: "text-neutral-900",
    intro: "moonLanterns",
    layout: "moonlit",
    seed: "proposal-starlit",
  },
  {
    id: "proposal-candlelight",
    category: "proposal",
    defaultAccent: "#E8B04A",
    defaultFont: "classic-serif",
    cardGradient: "from-red-950 via-rose-900 to-amber-600",
    cardTextClass: "text-neutral-900",
    intro: "candlelight",
    layout: "velvet",
    seed: "proposal-starlit",
  },
  {
    id: "proposal-will-you",
    category: "proposal",
    defaultAccent: "#1F4E8C",
    defaultFont: "elegant-script",
    cardGradient: "from-sky-100 via-white to-rose-100",
    cardTextClass: "text-neutral-900",
    intro: "scratch",
    layout: "letter",
    seed: "proposal-starlit",
  },
  {
    id: "proposal-beach-sunset",
    category: "proposal",
    defaultAccent: "#E76F51",
    defaultFont: "classic-serif",
    cardGradient: "from-orange-300 via-rose-200 to-sky-200",
    cardTextClass: "text-neutral-900",
    intro: "sunrise",
    layout: "arch",
    seed: "proposal-starlit",
  },
  {
    id: "proposal-rose-gold-ring",
    category: "proposal",
    defaultAccent: "#B76E79",
    defaultFont: "elegant-script",
    cardGradient: "from-rose-100 via-orange-50 to-rose-200",
    cardTextClass: "text-neutral-900",
    intro: "ringbox",
    layout: "sparkle",
    seed: "proposal-starlit",
  },
  {
    id: "birthday-balloon-party",
    category: "birthday",
    defaultAccent: "#FF6B6B",
    defaultFont: "modern-clean",
    cardGradient: "from-pink-200 via-yellow-100 to-sky-200",
    cardTextClass: "text-neutral-900",
    intro: "balloonPop",
    layout: "balloons",
    seed: "birthday-confetti",
  },
  {
    id: "birthday-neon-night",
    category: "birthday",
    defaultAccent: "#00E5FF",
    defaultFont: "modern-clean",
    cardGradient: "from-slate-950 via-cyan-900 to-fuchsia-700",
    cardTextClass: "text-neutral-900",
    intro: "spotlight",
    layout: "neon",
    seed: "birthday-confetti",
  },
  {
    id: "birthday-kids-fiesta",
    category: "birthday",
    defaultAccent: "#3A86FF",
    defaultFont: "modern-clean",
    cardGradient: "from-yellow-300 via-sky-200 to-pink-200",
    cardTextClass: "text-neutral-900",
    intro: "giftbox",
    layout: "kids",
    seed: "birthday-confetti",
  },
  {
    id: "birthday-golden-milestone",
    category: "birthday",
    defaultAccent: "#C9A24A",
    defaultFont: "luxe-didone",
    cardGradient: "from-neutral-900 via-stone-800 to-amber-500",
    cardTextClass: "text-neutral-900",
    intro: "foilCard",
    layout: "sparkle",
    seed: "birthday-confetti",
  },
  {
    id: "birthday-cake-candles",
    category: "birthday",
    defaultAccent: "#F15BB5",
    defaultFont: "modern-clean",
    cardGradient: "from-pink-200 via-rose-100 to-violet-200",
    cardTextClass: "text-neutral-900",
    intro: "cakeCandles",
    layout: "cake",
    seed: "birthday-confetti",
  },
  {
    id: "housewarming-griha-pravesam",
    category: "housewarming",
    defaultAccent: "#B8860B",
    defaultFont: "royal-cinzel",
    cardGradient: "from-red-900 via-orange-700 to-amber-400",
    cardTextClass: "text-neutral-900",
    intro: "thoranam",
    layout: "door",
    seed: "housewarming-terracotta",
  },
  {
    id: "housewarming-new-keys",
    category: "housewarming",
    defaultAccent: "#2A9D8F",
    defaultFont: "modern-clean",
    cardGradient: "from-stone-100 via-white to-teal-100",
    cardTextClass: "text-neutral-900",
    intro: "split",
    layout: "keys",
    seed: "housewarming-terracotta",
  },
  {
    id: "housewarming-boho-nest",
    category: "housewarming",
    defaultAccent: "#B5552E",
    defaultFont: "classic-serif",
    cardGradient: "from-orange-200 via-amber-100 to-lime-100",
    cardTextClass: "text-neutral-900",
    intro: "sunrise",
    layout: "arch",
    seed: "housewarming-terracotta",
  },
  {
    id: "housewarming-green-home",
    category: "housewarming",
    defaultAccent: "#3A7D44",
    defaultFont: "modern-clean",
    cardGradient: "from-lime-100 via-white to-emerald-200",
    cardTextClass: "text-neutral-900",
    intro: "bloom",
    layout: "garden",
    seed: "housewarming-terracotta",
  },
  {
    id: "housewarming-vastu-lamp",
    category: "housewarming",
    defaultAccent: "#9C4221",
    defaultFont: "royal-cinzel",
    cardGradient: "from-orange-900 via-amber-700 to-yellow-400",
    cardTextClass: "text-neutral-900",
    intro: "gopuram",
    layout: "temple",
    seed: "housewarming-terracotta",
  },
  {
    id: "baby-twinkle-star",
    category: "baby",
    defaultAccent: "#E48AB5",
    defaultFont: "elegant-script",
    cardGradient: "from-sky-200 via-indigo-100 to-pink-100",
    cardTextClass: "text-neutral-900",
    intro: "cradle",
    layout: "clouds",
    seed: "baby-moon",
  },
  {
    id: "baby-valaikaappu",
    category: "baby",
    defaultAccent: "#C2185B",
    defaultFont: "royal-cinzel",
    cardGradient: "from-pink-800 via-rose-600 to-emerald-500",
    cardTextClass: "text-neutral-900",
    intro: "marigoldCurtain",
    layout: "bangles",
    seed: "baby-moon",
  },
  {
    id: "baby-teddy-hug",
    category: "baby",
    defaultAccent: "#6FA3D8",
    defaultFont: "modern-clean",
    cardGradient: "from-sky-100 via-amber-50 to-orange-100",
    cardTextClass: "text-neutral-900",
    intro: "giftbox",
    layout: "teddy",
    seed: "baby-moon",
  },
  {
    id: "baby-naming-lotus",
    category: "baby",
    defaultAccent: "#C87A8E",
    defaultFont: "elegant-script",
    cardGradient: "from-pink-100 via-white to-teal-100",
    cardTextClass: "text-neutral-900",
    intro: "lotusBloom",
    layout: "lotus",
    seed: "baby-moon",
  },
  {
    id: "baby-shower-balloons",
    category: "baby",
    defaultAccent: "#5FA8C9",
    defaultFont: "elegant-script",
    cardGradient: "from-sky-100 via-pink-50 to-yellow-50",
    cardTextClass: "text-neutral-900",
    intro: "balloonPop",
    layout: "balloons",
    seed: "baby-moon",
  },
  {
    id: "corporate-gala-night",
    category: "corporate",
    defaultAccent: "#D4AF37",
    defaultFont: "royal-cinzel",
    cardGradient: "from-blue-950 via-slate-900 to-amber-500",
    cardTextClass: "text-neutral-900",
    intro: "spotlight",
    layout: "velvet",
    seed: "corporate-ticket",
  },
  {
    id: "corporate-tech-launch",
    category: "corporate",
    defaultAccent: "#6C63FF",
    defaultFont: "modern-clean",
    cardGradient: "from-slate-950 via-indigo-950 to-cyan-600",
    cardTextClass: "text-neutral-900",
    intro: "split",
    layout: "tech",
    seed: "corporate-ticket",
  },
  {
    id: "corporate-conference",
    category: "corporate",
    defaultAccent: "#1D4ED8",
    defaultFont: "modern-clean",
    cardGradient: "from-blue-100 via-white to-slate-200",
    cardTextClass: "text-neutral-900",
    intro: "ticket",
    layout: "editorial",
    seed: "corporate-ticket",
  },
  {
    id: "corporate-awards-night",
    category: "corporate",
    defaultAccent: "#C9A24A",
    defaultFont: "royal-cinzel",
    cardGradient: "from-neutral-950 via-yellow-900 to-amber-400",
    cardTextClass: "text-neutral-900",
    intro: "curtain",
    layout: "sparkle",
    seed: "corporate-ticket",
  },
  {
    id: "corporate-offsite",
    category: "corporate",
    defaultAccent: "#2F855A",
    defaultFont: "modern-clean",
    cardGradient: "from-emerald-100 via-amber-50 to-sky-100",
    cardTextClass: "text-neutral-900",
    intro: "sunrise",
    layout: "arch",
    seed: "corporate-ticket",
  },
];

export function getTemplateConfig(id: string): TemplateConfig {
  // Unknown ids fall back to the classic template by id, not TEMPLATES[0],
  // so reordering the gallery never changes the fallback.
  return TEMPLATES.find((t) => t.id === id) ?? TEMPLATES.find((t) => t.id === "traditional-gold")!;
}

export const TEMPLATE_IDS = TEMPLATES.map((t) => t.id);
